import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { CustomProvider } from "rsuite";
import NextAuthProvider from "../components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <EdgeStoreProvider>
            <CustomProvider>
              <main>
                <Navbar />
                {children}
              </main>
              <Toaster />
            </CustomProvider>
          </EdgeStoreProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
