import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import NextAuthProvider from "../components/Provider";
import ReactQueryProvider from "../components/RQProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "ThinkHub",
    template: "%s | ThinkHub",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="" lang="en">
      <body className={`${inter.className} `}>
        <NextAuthProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  );
}
